name: loging_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.0
  dio: ^5.7.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/IconApp.png"
  android_adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/loginIcon.svg
    - assets/IconApp.svg
    - assets/IconApp.png
