// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKH7ZiBQ6gkaSjbeJG6hrYTqBRO4-UKE',
    appId: '1:398360413179:web:1e141a18c7b834ce79015e',
    messagingSenderId: '398360413179',
    projectId: 'food-now-pbackend',
    authDomain: 'food-now-pbackend.firebaseapp.com',
    storageBucket: 'food-now-pbackend.appspot.com',
    measurementId: 'G-LLM9GGN5QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBq_H2zYjFZcLYjqx8Km7xFmeI_-kS_dI',
    appId: '1:398360413179:android:0b977a7c50ec254079015e',
    messagingSenderId: '398360413179',
    projectId: 'food-now-pbackend',
    storageBucket: 'food-now-pbackend.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYKH7ZiBQ6gkaSjbeJG6hrYTqBRO4-UKE',
    appId: '1:398360413179:web:bffca854a71e918879015e',
    messagingSenderId: '398360413179',
    projectId: 'food-now-pbackend',
    authDomain: 'food-now-pbackend.firebaseapp.com',
    storageBucket: 'food-now-pbackend.appspot.com',
    measurementId: 'G-DTB2DBG0W5',
  );
}
